#!/bin/bash

##################################################
# Author:	Meraj al Maksud
# Platform:	GNU/Linux
#
# This is a fix for the Bloody P91s mouse issue
# where the mouse won't respond when moving slowly
# towards left or up direction.
#
# Special thanks to @Graiden and @phemmer
# https://unix.stackexchange.com/a/719100/363734
# https://unix.stackexchange.com/a/144735/363734
##################################################

# Check if the script is being run with root privileges
if [ "$EUID" -ne 0 ]; then
	echo "Please run this script as root or with sudo."
	exit
fi

# Check if evtest and evsieve are installed
if [ ! command -v evtest &> /dev/null ] || [ ! command -v evsieve &> /dev/null ]; then
	echo "Please install evtest and evsieve: sudo apt install evtest evsieve"
	exit
fi

export devices=""

for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
	syspath="${sysdevpath%/dev}"
	devname="$(udevadm info -q name -p $syspath)"
	if [[ "$devname" =~ ^input/event.*$ ]]; then
	    eval "$(udevadm info -q property --export -p $syspath)"
	    if [ "$ID_SERIAL" = "COMPANY_USB_Device" ]; then
		export devices="$devices --input /dev/$devname grab"
	    fi
	fi
done

#echo "evsieve $devices --output"
evsieve $devices --output &
